"""Change detection engine for monitoring snapshots."""

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum

from app.monitoring.availability import HostAvailabilityResult, HostStatus
from app.monitoring.target import NetworkTarget
from app.monitoring.tcp_probe import PortStatus


class MonitoringEventType(StrEnum):
    """Types of events generated by the detection engine."""

    PORT_OPENED = "port_opened"
    PORT_CLOSED = "port_closed"
    HOST_BECAME_AVAILABLE = "host_became_available"
    HOST_BECAME_UNAVAILABLE = "host_became_unavailable"


@dataclass(frozen=True)
class MonitoringEvent:
    """A structured event representing a change in the monitored state."""

    event_type: MonitoringEventType
    target: NetworkTarget
    timestamp: datetime
    port: int | None = None
    previous_state: str | None = None
    current_state: str | None = None


def detect_changes(
    previous: HostAvailabilityResult | None,
    current: HostAvailabilityResult,
) -> list[MonitoringEvent]:
    """
    Compare two consecutive snapshots and return a list of relevant changes.

    Rules:
    - If `previous` is None, no events are generated (initial snapshot).
    - Host availability transitions generate HOST_BECAME_AVAILABLE / UNAVAILABLE.
    - Port state changes are evaluated only for ports present in BOTH snapshots.
    - PORT_OPENED is generated when a port transitions from any state to OPEN.
    - PORT_CLOSED is generated when a port transitions from OPEN to CLOSED.
    - Events are ordered deterministically: host events first, then port events
      sorted numerically by port number.
    """
    if previous is None:
        return []

    events: list[MonitoringEvent] = []

    # 1. Host Availability Events
    if (
        previous.status == HostStatus.AVAILABLE
        and current.status == HostStatus.UNAVAILABLE
    ):
        events.append(
            MonitoringEvent(
                event_type=MonitoringEventType.HOST_BECAME_UNAVAILABLE,
                target=current.target,
                timestamp=current.scan_result.started_at,
                previous_state=previous.status.value,
                current_state=current.status.value,
            )
        )
    elif (
        previous.status == HostStatus.UNAVAILABLE
        and current.status == HostStatus.AVAILABLE
    ):
        events.append(
            MonitoringEvent(
                event_type=MonitoringEventType.HOST_BECAME_AVAILABLE,
                target=current.target,
                timestamp=current.scan_result.started_at,
                previous_state=previous.status.value,
                current_state=current.status.value,
            )
        )

    # 2. Port Events
    prev_ports = {p.port: p for p in previous.scan_result.ports}
    curr_ports = {p.port: p for p in current.scan_result.ports}

    port_events: list[MonitoringEvent] = []

    # Evaluate only ports that exist in both snapshots to avoid false positives
    # when the user changes the monitoring configuration between scans.
    common_ports = sorted(set(prev_ports.keys()) & set(curr_ports.keys()))

    for port in common_ports:
        prev_probe = prev_ports[port]
        curr_probe = curr_ports[port]

        # Transition to OPEN from any other state
        if (
            prev_probe.status != PortStatus.OPEN
            and curr_probe.status == PortStatus.OPEN
        ):
            port_events.append(
                MonitoringEvent(
                    event_type=MonitoringEventType.PORT_OPENED,
                    target=current.target,
                    timestamp=current.scan_result.started_at,
                    port=port,
                    previous_state=prev_probe.status.value,
                    current_state=curr_probe.status.value,
                )
            )
        # Transition from OPEN to CLOSED
        elif (
            prev_probe.status == PortStatus.OPEN
            and curr_probe.status == PortStatus.CLOSED
        ):
            port_events.append(
                MonitoringEvent(
                    event_type=MonitoringEventType.PORT_CLOSED,
                    target=current.target,
                    timestamp=current.scan_result.started_at,
                    port=port,
                    previous_state=prev_probe.status.value,
                    current_state=curr_probe.status.value,
                )
            )

    events.extend(port_events)
    return events
